### ISSUE TITLE
Slow startup at initial installation or after force stop/clear cache

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#99] opened 2016-03-15 15:06 UTC
Note the 13 second delay between the 9th and 10th lines below.
The user will see a white screen during that period. Swiping 
right has no affect at this time. After that, the initial screen
displays normally and setup can continue.
```
03-15 09:51:26.246 11021-11021/org.mythtv.android W/System: ClassLoader referenced unknown path: /data/app/org.mythtv.android-1/lib/arm
03-15 09:51:26.250 11021-11021/org.mythtv.android I/InstantRun: BootstrapApplication created. Android package is org.mythtv.android, real application class is org.mythtv.android.presentation.AndroidApplication.
03-15 09:51:26.251 11021-11021/org.mythtv.android V/InstantRun: Cannot find external resources, not patching them in
03-15 09:51:26.251 11021-11021/org.mythtv.android I/InstantRun: Resource override is null
03-15 09:51:26.254 11021-11021/org.mythtv.android I/InstantRun: Last code patch: /data/data/org.mythtv.android/files/instant-run/dex/slice-slice_9_9d59c89459597679fc6f58fe3125cc35fc00b9aa-classes.dex
03-15 09:51:26.254 11021-11021/org.mythtv.android I/InstantRun: APK last modified: 1458052767000 < 1458052772000 code patch
03-15 09:51:26.255 11021-11021/org.mythtv.android I/InstantRun: Bootstrapping class loader with dex list [/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_9_9d59c89459597679fc6f58fe3125cc35fc00b9aa-classes.dex, /data/data/org.mythtv.android/files/instant-run/dex/slice-slice_8_b37d96a1e0c44f144dd123f857732c456d1af412-classes.dex, /data/data/org.mythtv.android/files/instant-run/dex/slice-slice_7_7f88559118af370b0508773c47042b5b623eac49-classes.dex, /data/data/org.mythtv.android/files/instant-run/dex/slice-slice_6_a0de9e2d73a767b6e0c96bc483611b14591555a8-classes.dex, /data/data/org.mythtv.android/files/instant-run/dex/slice-slice_5_da446cc33d6f8c72bbe1599b8f6f4e99786bcebe-classes.dex, /data/data/org.mythtv.android/files/instant-run/dex/slice-slice_4_7ef5c75b1b7895877a08d5c3219b195ad47afcef-classes.dex, /data/data/org.mythtv.android/files/instant-run/dex/slice-slice_3_c1f04da6db7bc039486c763ae3e1990c7d1b099d-classes.dex, /data/data/org.mythtv.android/files/instant-run/dex/slice-slice_2_9edac97490b2e801daf8adc13ce0011db32543e1-classes.dex, /data/data/org.mythtv.android/files/instant-run/dex/slice-slice_1_02137d7e9c05d657a263bfa74e3a886ac831c54c-classes.dex, /data/data/org.mythtv.android/files/instant-run/dex/slice-slice_0_b16d97bdf152c58a71c38e126cf4da77a9a2960e-classes.dex, /data/data/org.mythtv.android/files/instant-run/dex/slice-dependencies_989883a18a411873f02d8967170ad1249c87b170-classes.dex]
03-15 09:51:26.255 11021-11021/org.mythtv.android I/InstantRun: Native library path: /data/app/org.mythtv.android-1/lib/arm
03-15 09:51:26.256 11021-11021/org.mythtv.android I/InstantRun: Incremental dex path is /data/data/org.mythtv.android/files/instant-run/dex/slice-slice_9_9d59c89459597679fc6f58fe3125cc35fc00b9aa-classes.dex:/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_8_b37d96a1e0c44f144dd123f857732c456d1af412-classes.dex:/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_7_7f88559118af370b0508773c47042b5b623eac49-classes.dex:/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_6_a0de9e2d73a767b6e0c96bc483611b14591555a8-classes.dex:/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_5_da446cc33d6f8c72bbe1599b8f6f4e99786bcebe-classes.dex:/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_4_7ef5c75b1b7895877a08d5c3219b195ad47afcef-classes.dex:/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_3_c1f04da6db7bc039486c763ae3e1990c7d1b099d-classes.dex:/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_2_9edac97490b2e801daf8adc13ce0011db32543e1-classes.dex:/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_1_02137d7e9c05d657a263bfa74e3a886ac831c54c-classes.dex:/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_0_b16d97bdf152c58a71c38e126cf4da77a9a2960e-classes.dex:/data/data/org.mythtv.android/files/instant-run/dex/slice-dependencies_989883a18a411873f02d8967170ad1249c87b170-classes.dex
03-15 09:51:39.818 11021-11021/org.mythtv.android W/System: ClassLoader referenced unknown path: /data/app/org.mythtv.android-1/lib/arm
03-15 09:51:39.819 11021-11021/org.mythtv.android I/InstantRun: About to create real application of class name = org.mythtv.android.presentation.AndroidApplication
03-15 09:51:39.834 11021-11021/org.mythtv.android I/InstantRun: Created delegate app class successfully : class org.mythtv.android.presentation.AndroidApplication with class loader com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_9_9d59c89459597679fc6f58fe3125cc35fc00b9aa-classes.dex", dex file "/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_8_b37d96a1e0c44f144dd123f857732c456d1af412-classes.dex", dex file "/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_7_7f88559118af370b0508773c47042b5b623eac49-classes.dex", dex file "/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_6_a0de9e2d73a767b6e0c96bc483611b14591555a8-classes.dex", dex file "/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_5_da446cc33d6f8c72bbe1599b8f6f4e99786bcebe-classes.dex", dex file "/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_4_7ef5c75b1b7895877a08d5c3219b195ad47afcef-classes.dex", dex file "/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_3_c1f04da6db7bc039486c763ae3e1990c7d1b099d-classes.dex", dex file "/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_2_9edac97490b2e801daf8adc13ce0011db32543e1-classes.dex", dex file "/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_1_02137d7e9c05d657a263bfa74e3a886ac831c54c-classes.dex", dex file "/data/data/org.mythtv.android/files/instant-run/dex/slice-slice_0_b16d97bdf152c58a71c38e126cf4da77a9a2960e-classes.dex", dex file "/data/data/org.mythtv.android/files/instant-run/dex/slice-dependencies_989883a18a411873f02d8967170ad1249c87b170-classes.dex"],nativeLibraryDirectories=[/data/app/org.mythtv.android-1/lib/arm, /vendor/lib, /system/lib]]]
03-15 09:51:39.834 11021-11021/org.mythtv.android I/InstantRun: Created real app instance successfully :org.mythtv.android.presentation.AndroidApplication@7412d89
03-15 09:51:39.844 11021-11021/org.mythtv.android I/InstantRun: Starting server socket listening for package org.mythtv.android on android.net.LocalSocketAddress@5ae2daf
03-15 09:51:39.846 11021-11021/org.mythtv.android I/InstantRun: Started server for package org.mythtv.android
03-15 09:51:40.015 11021-11021/org.mythtv.android D/AppMainActivity: onCreate : enter
03-15 09:51:40.015 11021-11021/org.mythtv.android I/AppMainActivity: Current tag: mythtvplayer-1.1.13-1, Commit: 04fe886
```

**Comment by dmfrey** [comment] 2016-03-15 15:14
Has this happened before?  Was this on installation? Was it after you set
the backend url?

**Comment by billmeek** [comment] 2016-03-15 15:32
It's fairly new. It only happens after force stop/clear cache or after
removing the app followed by a new download.

It happens before setting the backend IP.

I recall there was a commit that sent the user
to the Settings page if the backend IP wasn't set
but haven't found it.

**Comment by dmfrey** [comment] 2016-03-15 15:55
Sounds like it is a part of the installation process android uses with
multidex enabled (after looking at the stack trace posted). Unfortunately,
multidex is going to be a requirement going forward, I feel. The problem is
the static method count can't be greater than 65536 count. It is a known
issue on Android and has to do with how the dex processes the files into
final APK. I, personally, haven't experienced this, however, I do end up
waiting for full gradle builds while I am iterating and testing (so maybe
it is getting lost in there). Hopefully, Stop, Clear Cache, etc. will not
be called all that often by the users.

**Comment by billmeek** [comment] 2016-03-21 23:29
When installed from the Play Store, the slow startup doesn't occur.

**Comment by dmfrey** [comment] 2016-03-23 01:27
This only seems to be an issue with a full build coming out of the IDE over ADB.  Closing for now.

**Closed by dmfrey** 2016-03-23 01:27 UTC
Labels: bug
