### ISSUE TITLE
SocketTimeout prevents programme information from loading

### ISSUE THREAD

**Issue by SingingDwarf** [MythTV-Clients/MythtvPlayerForAndroid#113] opened 2016-04-03 22:47 UTC
_Upcoming_ and _Encoders_ both display the correct information but _Recent_, _Watch Recordings_ and _Watch Videos_ all result in the message "Can't connect to mythbackend".

It transpires that the Recordings table contains a number (>340) entries with an empty inetref entry.

GetRecordedList attached.

There are no errors reported in mythbackend.log

I'm running MythTV 0.27.6+fixes.20160 and MythTV Player 2.0.2

[GetRecordedList-ford.txt](https://github.com/MythTV-Clients/MythtvPlayerForAndroid/files/201602/GetRecordedList-ford.txt)

**Comment by billmeek** [comment] 2016-04-03 23:39
Hi, I know I've only tested with a mere 200+ recordings, not: 5287
or 12168589 characters. I do have a few recordings without inetrefs
just for testing and they load A-OK.

@SingingDwarf:
Are you looking at LogCat or something else that tells you that the
empty inetrefs are the cause of the "Can't connect to mythbackend"
messages?

@dmfrey I see that GetRecordedList is called at startup and then
it's called again when the Watch Recording screen is entered. And
in the same second, GetTitleInfoList is called. Could the 2nd
GetRecordedList be eliminated?

**Comment by dmfrey** [comment] 2016-04-04 00:02
@billmeek, the first one calls it with a limit of 10 and in descending
order, much like the status page does on mythweb. Plus, this isn't cached.

@SingingDwarf I was also going to recommend you hook up to ADB if you can
to get a snapshot of the logs.  I have a unit test looking for the data we
use on the screens and it is parsing ok. I will commit it to the branch,
but it does require a hard path to the file, so probably won't be merged
unless we have bug somewhere.

**Comment by billmeek** [comment] 2016-04-04 00:15
@dmfrey, 10 would make sense, but Wireshark says
that both calls are the same:
```
Full request URI: http://[fdf9:a66:2cd8:1::200]:6544/Dvr/GetRecordedList?Descending=true
Full request URI: http://[fdf9:a66:2cd8:1::200]:6544/Dvr/GetRecordedList?Descending=true
```
Both are set  up with count=-1 in LogCat. Let me see if I can change -1 to10 somewhere.

**Comment by dmfrey** [comment] 2016-04-04 00:32
it is getting the whole list. I can correct this. DvrDataRepository.recent()

**Comment by SingingDwarf** [comment] 2016-04-04 09:14
@billmeek No - it wassuggested by @dmfrey 

I'm off on holiday today for the week, but I'll try and grab some logs when I get back.

**Comment by dmfrey** [comment] 2016-04-08 01:47
@SingingDwarf  I added some tests to try to reproduce your error and no luck. Next step would be to get an adb log from your system.

**Comment by SingingDwarf** [comment] 2016-04-11 20:29
Apologies for the delay, I have been away on hols.

I have uploaded a log file [here](http://4gp.me/ba3s/1460406191877.txt) - which shows Mythtv Player loading, the Recent screen failing to load, the Encoders and then Upcoming screens working correctly - followed by the Recent screen failing to load again.

**Comment by SingingDwarf** [comment] 2016-04-11 20:32
I have also uploaded a [second log](http://m.uploadedit.com/ba3s/146040661798.log), which shows the (already open) Mythtv Player attempting to show the Watch Recordings screen which again fails.

**Comment by dmfrey** [comment] 2016-04-27 18:30
@SingingDwarf I am seeing a socket timeout exception in there. Sounds like a failure maintaining a connection. Any luck lately?

**Comment by dmfrey** [comment] 2016-04-27 18:41
ReadTimeout is current set to 10 seconds.  Maybe we should bump this 30 or 40 seconds. Thoughts?

**Comment by SingingDwarf** [comment] 2016-04-27 22:58
I'm still having no joy - on either of my two devices I'm afraid.

I note from the log that the call `http://[mythbackend]:6544/Dvr/GetRecordedList?Descending=true` is being made.

I've done some testing using the Page Load Time extension in Chrome - the call `http://[mythbackend]:6544/Dvr/GetRecordedList?StartIndex=0&Count=300&Descending=true` takes 6.2 seconds to load. When the count is 500 it takes 8.4 seconds and at 1,000 it takes 21 seconds.

With my 5,000 odd recordings, I think a timeout larger than 40 seconds may be required.

**Comment by dmfrey** [comment] 2016-04-27 23:49
I am making it configurable in the settings. You will want to probably set
both the read and connect timeout. It will be in this forthcoming commit.
Would you like me to send you an apk to test with? Or are you able to build
from source?

**Comment by SingingDwarf** [comment] 2016-04-28 12:48
Sorry, but I'll need an apk :-(

**Comment by dmfrey** [comment] 2016-04-28 13:03
Ok, i have to update the android tv code first before I can build this.
Then I will send you a debug apk to try out.

**Closed** 2016-04-29 00:20 UTC

**Comment by dmfrey** [comment] 2016-04-29 03:01
@SingingDwarf Email me and I will send you and APK to test. dmfrey at gmail
